import type { Pair } from "../types";
import { date as fmtDate, ron as fmtRon } from "./format";

/* Type-only handle on docx's TableCell so we can annotate the local
 * cell-builder helper. The runtime `TableCell` binding comes from a
 * dynamic `import("docx")` inside exportToDocx so the library still
 * doesn't load until the user actually picks the format. */
import type { TableCell as DocxTableCell } from "docx";

/* ──────────────────────────────────────────────────────────────────────
 * Export module
 *
 * One projection layer + three lazy-loaded exporters (PDF, XLSX, DOCX).
 * Each exporter builds an in-memory file from the same `Row[]`, hands
 * the bytes to Tauri's native save dialog, then writes through the
 * fs plugin when the user confirms a path. Cancel returns null and
 * the caller treats that as a no-op.
 *
 * The heavy libraries (jspdf, jspdf-autotable, exceljs, docx) are
 * dynamic-imported so they only ship to the WebView when the user
 * actually clicks Export — the cold-start bundle stays slim even
 * with three formats wired up.
 *
 * Only "ready" pairs contribute. Pending / extracting / error rows
 * are silently skipped because their numeric columns would be blank
 * and break Excel formulas and PDF totals. The "#" column in the
 * exports keeps the original queue index so the user can still see
 * which row in the app a given printed line came from.
 * ────────────────────────────────────────────────────────────────────── */

interface Row {
  idx: number;          // 1-based index in the original queue
  awb: string;
  factura: string;      // "INV-123" or "INV-123 (DUP)"
  date: string;         // ISO yyyy-mm-dd; formatters at the edge turn it human-readable
  service: string;
  kg: number;
  km: number;
  livrari: number;
  baza: number;
  kmExtra: number;      // 0 means "didn't apply" — kept numeric so Excel can still SUM
  increment: number;
  weekend: number;
  carrier: number;      // carrier subtotal (was `totalVat21`); muted in exports
  commission: number;   // commission (was Ploiești cut)
  total: number;        // customer total — the billable number printed on the invoice
}

interface Projection {
  rows: Row[];
  total: number;
  readyCount: number;
  totalCount: number;
  generatedAt: Date;
}

/** Optional metadata threaded through every exporter. `day` is the
 *  ISO YYYY-MM-DD the caller is exporting (the visible day-tab in the
 *  UI). It changes the suggested filename and adds a "Ziua: ..." line
 *  to the in-document header so the printed page identifies which
 *  day's batch it represents. */
export interface ExportOptions {
  day?: string;
}

/** Pure: flatten the queue into a structured row list + grand total.
 *  Used by all three exporters. Exposed for tests / debugging. */
export function pairsToRows(pairs: Pair[]): Projection {
  const rows: Row[] = [];
  let runningTotal = 0;
  for (let i = 0; i < pairs.length; i++) {
    const p = pairs[i];
    // Guard satisfies `noUncheckedIndexedAccess`; the loop bound makes
    // the undefined branch unreachable at runtime.
    if (!p || p.status.kind !== "ready") continue;
    const { service, edits, breakdown } = p.status;
    rows.push({
      idx: i + 1,
      awb: edits.awb_number,
      factura:
        edits.invoice_number + (edits.invoice_is_duplicate ? " (DUP)" : ""),
      date: edits.delivery_date,
      service,
      kg: edits.weight_kg,
      km: edits.distance_extra_km,
      livrari: edits.num_deliveries,
      baza: breakdown.baseTariff,
      kmExtra: breakdown.extraKmCost,
      increment: breakdown.incrementCost,
      weekend: breakdown.weekendSurcharge,
      carrier: breakdown.totalVat21,
      commission: breakdown.commission,
      total: breakdown.customerTotal,
    });
    runningTotal += breakdown.customerTotal;
  }
  return {
    rows,
    total: runningTotal,
    readyCount: rows.length,
    totalCount: pairs.length,
    generatedAt: new Date(),
  };
}

/* ── Filename + save helpers ──────────────────────────────────────── */

type Ext = "pdf" | "xlsx" | "docx";

/** Local-tz YYYY-MM-DD so the suggested filename matches what the
 *  user sees on their clock, not UTC. */
function ymd(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

/** Build a suggested filename. When the caller knows which day is
 *  being exported, that day wins over the "right now" timestamp —
 *  the file is *about* that day even if it's generated later. */
function defaultName(ext: Ext, generatedAt: Date, day?: string): string {
  const stamp = day && /^\d{4}-\d{2}-\d{2}$/.test(day) ? day : ymd(generatedAt);
  return `centralizator-${stamp}.${ext}`;
}

/**
 * Hand the generated bytes to Tauri's native save dialog and write
 * the user-chosen path via the fs plugin. Returns the absolute path on
 * success, or null when the user cancels the dialog.
 *
 * Both plugins are imported dynamically here too: a user who never
 * exports never pays the cost of pulling them into the bundle either.
 */
async function saveBinary(
  bytes: Uint8Array,
  ext: Ext,
  generatedAt: Date,
  filterName: string,
  day?: string,
): Promise<string | null> {
  const { save } = await import("@tauri-apps/plugin-dialog");
  const { writeFile } = await import("@tauri-apps/plugin-fs");
  const chosen = await save({
    defaultPath: defaultName(ext, generatedAt, day),
    filters: [{ name: filterName, extensions: [ext] }],
  });
  if (!chosen) return null;
  await writeFile(chosen, bytes);
  return chosen;
}

/** "Ziua: 30.05.2026 · 12 / 20 perechi · Total: 1234,56 RON" — the
 *  one-liner that anchors every export header to the day it represents.
 *  Falls back to today's generated-at when the caller didn't pass a
 *  day, so older callers still get a sensible header. */
function metaLine(proj: Projection, day?: string): string {
  const dayPart = day ? `Ziua: ${fmtDate(day)} · ` : "";
  return `${dayPart}${proj.readyCount} din ${proj.totalCount} perechi calculate · Total: ${fmtRon(proj.total)}`;
}

/** Currency for cells. Conditional surcharges render "—" at zero so
 *  the export matches what the user sees in the app's grid; the
 *  Excel writer ignores this and keeps raw 0 so SUM() still works. */
function fmtCur(n: number, blankZero = false): string {
  return blankZero && n === 0 ? "—" : fmtRon(n);
}

/* ══════════════════════════════════════════════════════════════════
 * PDF — jsPDF + jsPDF-AutoTable, A4 landscape
 * ══════════════════════════════════════════════════════════════════ */

export async function exportToPdf(
  pairs: Pair[],
  opts: ExportOptions = {},
): Promise<string | null> {
  const proj = pairsToRows(pairs);
  if (proj.rows.length === 0) {
    throw new Error("Nu există perechi calculate pentru export.");
  }

  const { jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  // A4 landscape: 13 columns fit cleanly across ~760pt of usable width.
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Title block ──────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(37, 34, 30); // ink-800
  doc.text("Centralizator", 40, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(109, 102, 92); // ink-500
  doc.text("Stalexone Trans", 40, 56);
  doc.text(
    `Generat: ${proj.generatedAt.toLocaleString("ro-RO")}`,
    pageWidth - 40,
    56,
    { align: "right" },
  );
  doc.text(metaLine(proj, opts.day), 40, 72);

  autoTable(doc, {
    startY: 90,
    head: [[
      "#", "AWB", "Factură", "Data", "Serviciu",
      "kg", "km", "Liv.",
      "Bază", "Km+", "Inc.", "Wkd",
      "Tarif transp.", "Comision", "Total",
    ]],
    body: proj.rows.map((r) => [
      r.idx,
      r.awb,
      r.factura,
      fmtDate(r.date),
      r.service,
      r.kg.toFixed(2),
      r.km.toFixed(0),
      r.livrari.toFixed(0),
      fmtCur(r.baza),
      fmtCur(r.kmExtra, true),
      fmtCur(r.increment, true),
      fmtCur(r.weekend, true),
      fmtCur(r.carrier),
      fmtCur(r.commission),
      fmtCur(r.total),
    ]),
    foot: [[
      "", "", "", "", "Total",
      "", "", "",
      "", "", "", "",
      "", "",
      fmtRon(proj.total),
    ]],
    styles: { fontSize: 8, cellPadding: 4, valign: "middle" },
    // Header bar matches canvas-200; foot bar matches coral-500 — same
    // visual language as the in-app PairsTable, so a printed export
    // looks like the screen it came from.
    headStyles: {
      fillColor: [236, 229, 210],
      textColor: [58, 53, 47],
      fontStyle: "bold",
    },
    footStyles: {
      fillColor: [197, 111, 78],
      textColor: [251, 248, 241],
      fontStyle: "bold",
      halign: "right",
    },
    bodyStyles: { textColor: [37, 34, 30] },
    alternateRowStyles: { fillColor: [244, 239, 227] },
    columnStyles: {
      0: { halign: "center", cellWidth: 22 },
      1: { cellWidth: 95 },
      2: { cellWidth: 95 },
      3: { halign: "center", cellWidth: 55 },
      4: { halign: "center", cellWidth: 65 },
      5: { halign: "right", cellWidth: 35 },
      6: { halign: "right", cellWidth: 35 },
      7: { halign: "right", cellWidth: 30 },
      8: { halign: "right", cellWidth: 50 },
      9: { halign: "right", cellWidth: 45 },
      10: { halign: "right", cellWidth: 45 },
      11: { halign: "right", cellWidth: 45 },
      12: { halign: "right", cellWidth: 60 }, // carrier subtotal (muted)
      13: { halign: "right", cellWidth: 60 }, // commission
      14: { halign: "right", cellWidth: 72, fontStyle: "bold", textColor: [139, 72, 48] }, // customer total
    },
    margin: { left: 40, right: 40 },
  });

  const buf = new Uint8Array(doc.output("arraybuffer") as ArrayBuffer);
  return saveBinary(buf, "pdf", proj.generatedAt, "PDF", opts.day);
}

/* ══════════════════════════════════════════════════════════════════
 * XLSX — ExcelJS workbook with live SUM() formulas
 * ══════════════════════════════════════════════════════════════════ */

export async function exportToXlsx(
  pairs: Pair[],
  opts: ExportOptions = {},
): Promise<string | null> {
  const proj = pairsToRows(pairs);
  if (proj.rows.length === 0) {
    throw new Error("Nu există perechi calculate pentru export.");
  }

  // ExcelJS is published as a default export; named imports don't work.
  const ExcelJS = (await import("exceljs")).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = "Centralizator";
  wb.created = proj.generatedAt;

  // Worksheet name carries the day so a workbook opened from disk
  // identifies its contents at a glance from the bottom tab. Excel
  // caps sheet names at 31 chars; "Ziua DD.MM.YYYY" is 15.
  const sheetName = opts.day ? `Ziua ${fmtDate(opts.day)}` : "Centralizator";
  // Freeze the title + header band so the user can scroll the body.
  const ws = wb.addWorksheet(sheetName, {
    views: [{ state: "frozen", ySplit: 4 }],
    properties: { defaultRowHeight: 18 },
  });

  // Excel "character" widths roughly proportional to the in-app grid.
  ws.columns = [
    { key: "idx", width: 5 },
    { key: "awb", width: 18 },
    { key: "factura", width: 18 },
    { key: "date", width: 12 },
    { key: "service", width: 12 },
    { key: "kg", width: 9 },
    { key: "km", width: 7 },
    { key: "livrari", width: 7 },
    { key: "baza", width: 13 },
    { key: "kmExtra", width: 13 },
    { key: "increment", width: 13 },
    { key: "weekend", width: 13 },
    { key: "carrier", width: 15 },
    { key: "commission", width: 13 },
    { key: "total", width: 18 },
  ];

  // ── Title row ────────────────────────────────────────────────────
  ws.mergeCells("A1:O1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "Centralizator · Stalexone Trans";
  titleCell.font = { name: "Calibri", size: 16, bold: true, color: { argb: "FF25221E" } };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };
  ws.getRow(1).height = 26;

  ws.mergeCells("A2:O2");
  const subCell = ws.getCell("A2");
  const dayLabel = opts.day ? `Ziua: ${fmtDate(opts.day)} · ` : "";
  subCell.value = `${dayLabel}Generat: ${proj.generatedAt.toLocaleString("ro-RO")} · ${proj.readyCount} din ${proj.totalCount} perechi`;
  subCell.font = { name: "Calibri", size: 10, italic: true, color: { argb: "FF6D665C" } };
  ws.getRow(2).height = 16;

  // Row 3 is a 6-pt spacer for breathing room before the header.
  ws.getRow(3).height = 6;

  // ── Header row 4 ─────────────────────────────────────────────────
  const headerRow = ws.addRow([
    "#", "AWB", "Factură", "Data", "Serviciu",
    "kg", "km", "Liv.",
    "Bază (RON)", "Km+ (RON)", "Inc. (RON)", "Wkd (RON)",
    "Tarif transp. (RON)", "Comision (RON)", "Total (RON)",
  ]);
  headerRow.font = { bold: true, color: { argb: "FF3A352F" } };
  headerRow.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
  headerRow.eachCell((c) => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFECE5D2" } };
    c.border = { bottom: { style: "thin", color: { argb: "FFB9B0A0" } } };
  });
  headerRow.height = 26;

  // ── Data rows ────────────────────────────────────────────────────
  const RON = '#,##0.00" RON"';
  const firstDataRow = 5;

  for (const r of proj.rows) {
    const row = ws.addRow([
      r.idx,
      r.awb,
      r.factura,
      r.date,
      r.service,
      r.kg,
      r.km,
      r.livrari,
      r.baza,
      r.kmExtra,
      r.increment,
      r.weekend,
      r.carrier,
      r.commission,
      r.total,
    ]);
    row.getCell(1).alignment = { horizontal: "center" };

    // Parse the ISO date into a real Date so Excel sorts and filters
    // by chronological order, not lexicographic string order.
    const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(r.date);
    // The regex above has exactly three capture groups, so when it
    // matches `m[1..3]` are always strings — the non-null assertions
    // satisfy `noUncheckedIndexedAccess` without hiding any real bug.
    if (m) row.getCell(4).value = new Date(+m[1]!, +m[2]! - 1, +m[3]!);
    row.getCell(4).numFmt = "dd.mm.yyyy";
    row.getCell(4).alignment = { horizontal: "center" };

    row.getCell(5).alignment = { horizontal: "center" };
    row.getCell(6).numFmt = "0.00";
    row.getCell(7).numFmt = "0";
    row.getCell(8).numFmt = "0";
    // RON format on cols 9..15 (Bază, Km+, Inc., Wkd, Tarif transp., Comision, Total).
    for (let c = 9; c <= 15; c++) row.getCell(c).numFmt = RON;
    // Col 15 = customer total → bold accent, matches in-app PairsTable.
    row.getCell(15).font = { bold: true, color: { argb: "FF8B4830" } };
  }

  const lastDataRow = firstDataRow + proj.rows.length - 1;

  // ── Totals row with live SUM() ───────────────────────────────────
  // Using formulas (not pre-computed values) so if the user
  // hand-edits a cell after opening the file, the total self-heals.
  // 15 cells, 4 leading blanks, "Total" in col 5, then blanks through 8.
  const totalsRow = ws.addRow([
    "", "", "", "", "Total", "", "", "",
    "", "", "", "",
    "", "", "",
  ]);
  totalsRow.height = 24;
  totalsRow.eachCell((c) => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFC56F4E" } };
  });
  totalsRow.font = { bold: true, color: { argb: "FFFBF8F1" } };
  totalsRow.getCell(5).alignment = { horizontal: "right" };

  // SUM formulas for cols 9..15 (Bază, Km+, Inc., Wkd, Tarif transp.,
  // Comision, Total). Customer total in col 15 is the bottom line.
  for (let c = 9; c <= 15; c++) {
    const col = String.fromCharCode("A".charCodeAt(0) + c - 1);
    totalsRow.getCell(c).value = {
      formula: `SUM(${col}${firstDataRow}:${col}${lastDataRow})`,
    };
    totalsRow.getCell(c).numFmt = RON;
  }
  totalsRow.getCell(15).font = {
    bold: true,
    size: 12,
    color: { argb: "FFFBF8F1" },
  };

  const arrBuf = await wb.xlsx.writeBuffer();
  return saveBinary(
    new Uint8Array(arrBuf as ArrayBuffer),
    "xlsx",
    proj.generatedAt,
    "Excel",
    opts.day,
  );
}

/* ══════════════════════════════════════════════════════════════════
 * DOCX — docx library, A4 landscape table
 * ══════════════════════════════════════════════════════════════════ */

export async function exportToDocx(
  pairs: Pair[],
  opts: ExportOptions = {},
): Promise<string | null> {
  const proj = pairsToRows(pairs);
  if (proj.rows.length === 0) {
    throw new Error("Nu există perechi calculate pentru export.");
  }

  const {
    Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
    HeadingLevel, AlignmentType, WidthType, BorderStyle, PageOrientation,
  } = await import("docx");

  // Palette mirrored from the app theme so the doc reads as a
  // Centralizator export, not a generic Word table.
  const INK = "25221E";
  const INK_500 = "6D665C";
  const CANVAS_50 = "FBF8F1";
  const CANVAS_200 = "ECE5D2";
  const CORAL_500 = "C56F4E";
  const CORAL_700 = "8B4830";

  const border = { style: BorderStyle.SINGLE, size: 4, color: "B9B0A0" };
  const allBorders = {
    top: border, bottom: border, left: border, right: border,
    insideHorizontal: border, insideVertical: border,
  };

  type Align = "left" | "right" | "center";
  function tcell(
    text: string,
    opts?: { bold?: boolean; bg?: string; color?: string; align?: Align },
  ): DocxTableCell {
    return new TableCell({
      shading: opts?.bg ? { fill: opts.bg } : undefined,
      children: [
        new Paragraph({
          alignment:
            opts?.align === "right"
              ? AlignmentType.RIGHT
              : opts?.align === "center"
              ? AlignmentType.CENTER
              : AlignmentType.LEFT,
          children: [
            new TextRun({
              text,
              bold: opts?.bold,
              color: opts?.color ?? INK,
              size: 18, // half-points → 9pt
              font: "Calibri",
            }),
          ],
        }),
      ],
    });
  }

  const headerLabels = [
    "#", "AWB", "Factură", "Data", "Serviciu",
    "kg", "km", "Liv.",
    "Bază", "Km+", "Inc.", "Wkd",
    "Tarif transp.", "Comision", "Total",
  ];

  const headerAligns: Align[] = [
    "center", "left", "left", "center", "center",
    "right", "right", "right",
    "right", "right", "right", "right",
    "right", "right", "right",
  ];

  const headerRow = new TableRow({
    tableHeader: true,
    children: headerLabels.map((h, i) =>
      tcell(h, { bold: true, bg: CANVAS_200, align: headerAligns[i] }),
    ),
  });

  const dataRows = proj.rows.map((r) =>
    new TableRow({
      children: [
        tcell(String(r.idx), { align: "center" }),
        tcell(r.awb),
        tcell(r.factura),
        tcell(fmtDate(r.date), { align: "center" }),
        tcell(r.service, { align: "center" }),
        tcell(r.kg.toFixed(2), { align: "right" }),
        tcell(r.km.toFixed(0), { align: "right" }),
        tcell(r.livrari.toFixed(0), { align: "right" }),
        tcell(fmtCur(r.baza), { align: "right" }),
        tcell(fmtCur(r.kmExtra, true), { align: "right" }),
        tcell(fmtCur(r.increment, true), { align: "right" }),
        tcell(fmtCur(r.weekend, true), { align: "right" }),
        tcell(fmtCur(r.carrier), { align: "right" }),
        tcell(fmtCur(r.commission), { align: "right" }),
        tcell(fmtCur(r.total), { align: "right", bold: true, color: CORAL_700 }),
      ],
    }),
  );

  // Totals row: coral background, cream text — same accent as the
  // in-app sticky bottom row. Bottom-line number sits in col 14
  // (zero-indexed) now that we added the two commission columns.
  const totalsCells: DocxTableCell[] = headerLabels.map((_, i) => {
    if (i === 4) {
      return tcell("Total", {
        bg: CORAL_500, bold: true, color: CANVAS_50, align: "right",
      });
    }
    if (i === 14) {
      return tcell(fmtRon(proj.total), {
        bg: CORAL_500, bold: true, color: CANVAS_50, align: "right",
      });
    }
    return tcell("", { bg: CORAL_500 });
  });
  const totalsRow = new TableRow({ children: totalsCells });

  const table = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: allBorders,
    rows: [headerRow, ...dataRows, totalsRow],
  });

  const doc = new Document({
    creator: "Centralizator",
    title: "Centralizator export",
    sections: [
      {
        properties: {
          page: {
            size: { orientation: PageOrientation.LANDSCAPE },
            // 0.5" margins in twentieths of a point.
            margin: { top: 720, right: 720, bottom: 720, left: 720 },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({ text: "Centralizator", bold: true, size: 36, color: INK }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Stalexone Trans", color: INK_500, size: 20 }),
            ],
          }),
          new Paragraph({
            spacing: { after: 240 },
            children: [
              new TextRun({
                text:
                  (opts.day ? `Ziua: ${fmtDate(opts.day)} · ` : "") +
                  `Generat: ${proj.generatedAt.toLocaleString("ro-RO")} · ${proj.readyCount} din ${proj.totalCount} perechi`,
                color: INK_500,
                size: 18,
                italics: true,
              }),
            ],
          }),
          table,
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const buf = new Uint8Array(await blob.arrayBuffer());
  return saveBinary(buf, "docx", proj.generatedAt, "Word", opts.day);
}
